# Generated by Django 4.1.7 on 2023-04-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetone', '0002_alter_restaurant_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=80),
        ),
    ]
